name: build
on:
  workflow_dispatch:
jobs:
  compile:
    name: build packages
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
          image: josdehaes/asahi-alarm-pkgbuild:latest
          options: -v ${{ github.workspace }}:/home/user/PKGBUILDs
          run: |
            ./build.sh asahi-scripts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          path: |
            packages/*.pkg.tar.xz
