name: build
on:
  workflow_dispatch:
jobs:
  mesa:
    name: build mesa overlay packages
    runs-on: ubuntu-24.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Display runner UID and GID
        run: |
          echo "Runner UID: $(id -u)"
          echo "Runner GID: $(id -g)"
        id: get_ids
      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
          image: josdehaes/asahi-alarm-pkgbuild-mesa:latest
          options: >
            -v ${{ github.workspace }}:/home/user/PKGBUILDs --user 1001:116

          run: |
            cd mesa-asahi && makepkg -sC --noconfirm
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: overlays
          path: |
            mesa-asahi/mesa-asahi-fex-emu-overlay-i386*
            mesa-asahi/mesa-asahi-fex-emu-overlay-x86_64*
  compile:
    name: build packages
    runs-on: ubuntu-24.04-arm
    needs: [mesa]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Display runner UID and GID
        run: |
          echo "Runner UID: $(id -u)"
          echo "Runner GID: $(id -g)"
        id: get_ids
      - name: download overlays
        uses: actions/download-artifact@v4
        with:
          name: overlays
          path: packages
      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
          image: josdehaes/asahi-alarm-pkgbuild:latest
          options: >
            -v ${{ github.workspace }}:/home/user/PKGBUILDs --user 1001:116 -e B64=${{ secrets.B64 }} -e GPG_PASSPHRASE=${{ secrets.GPG_PASSPHRASE }}

          run: |
            set -e
            printf "%s" "$B64" | base64 -d | gpg --batch --no-tty --import
            sudo pacman -Syu
            ./build.sh
            cd packages
            ls
            for file in *; do
              echo "$GPG_PASSPHRASE" | gpg --local-user 12CE6799A94A3F1B5DDFFE88F576553597FB8FEB --pinentry-mode loopback --passphrase-fd 0 --detach-sign "$file"
              repo-add --key 12CE6799A94A3F1B5DDFFE88F576553597FB8FEB --sign asahi-alarm.db.tar.gz "$file"
            done
            ls
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: |
            packages/*
