name: test
on:
  workflow_dispatch:
jobs:
  job2:
    name: bar
    runs-on: ubuntu-24.04
    steps:
      - name: Authenticate GitHub CLI
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release download aarch64 --repo asahi-alarm/asahi-alarm --pattern asahi-scripts*
          ls
